import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SectionVisibility, SectionComponents } from '../enums/SectionVisibility.enum';
import Home from '../components/Sections/Home';
import About from '../components/Sections/About';
import UnderConstruction from '../components/Common/UnderConstruction';
import PreLoader from '../components/Common/PreLoader';

import React  from 'react';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  // const router = useRouter();
  // const [currentSection, setCurrentSection] = useState<string>('');

  // useEffect(() => {
  //   const it = router.query;
  //   // setCurrentSection(it.section as SectionVisibility);
  //   setShowPreloader(true);
  // }, [router.asPath, router.query]);

  const renderSection = () => {
    const activeSections = SectionComponents[SectionVisibility.ACTIVE] || [];
    // const sectionToSee =  activeSections.find((active) => active === currentSection)
    // if(sectionToSee === 'Home'){
    //   return <Home key={sectionToSee} />
    // }
    // else if (sectionToSee === 'About'){
    //   return <About key={sectionToSee} />
    // }
    // else{
    //   const isUnderConstruction = SectionComponents[SectionVisibility.ALL].includes(currentSection)
    //   if(isUnderConstruction){null
    //     return <UnderConstruction key={currentSection} />
    //   }
    //   else{
    //     if(!!currentSection){
    //       return <h1>404</h1>
    //     }
    //     else{
          return <Home key='Home' />
      //   }
        
      // }
      
    // }
  };
  // const [showPreloader, setShowPreloader] = useState(false);

  return (
    <div className="background-container">
      {/* {<PreLoader />} */}
      {renderSection()}
      {children}
    </div>
  );
};

